name: Release Management

on:
  release:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - waldbauer
        - sebastian
      message:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }} ${{ github.event.inputs.name }}"
